// Liste de départ du filtre (insultes, harcèlement, contenus sexuels, haine), insérée par la migration
// « forum » et par le seed ; l'administration la complète ensuite (termes en wolof notamment).
// Mots écartés pour éviter des faux positifs dans les cours (voir DOCS/moderation.md) :
// « sexe » (SVT), « chatte » (l'animal), « con » (trop court), « crève » (« une crève » = un rhume).
export const TERMES_INITIAUX: readonly string[] = [
  "abruti",
  "attardé",
  "bamboula",
  "bâtard",
  "bite",
  "bougnoule",
  "branlette",
  "branleur",
  "connard",
  "connasse",
  "couilles",
  "enculé",
  "enculer",
  "fdp",
  "ferme ta gueule",
  "fils de pute",
  "gouine",
  "grognasse",
  "mongol",
  "nègre",
  "negro",
  "nique ta mère",
  "nique ta race",
  "ntm",
  "nude",
  "nudes",
  "pd",
  "pédé",
  "pétasse",
  "porno",
  "pouffiasse",
  "pute",
  "putain",
  "salaud",
  "sale arabe",
  "sale juif",
  "sale noir",
  "salope",
  "suicide toi",
  "ta gueule",
  "tapette",
  "tg",
  "va crever",
  "va mourir",
  "va te pendre",
  "youpin",
];
